name: Daily Deploy

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate static JSON
        run: npm --workspace backend run generate-static
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build frontend
        run: npm --workspace frontend run predeploy

      - name: Deploy to GitHub Pages
        run: npm --workspace frontend run deploy
